# Generated by Django 5.0.6 on 2024-05-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='viewed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
