# Generated by Django 5.0.6 on 2024-05-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('r', 'Red'), ('g', 'Green'), ('b', 'Blue'), ('y', 'Yellow'), ('c', 'Cyan'), ('m', 'Magenta'), ('w', 'White'), ('k', 'Black')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XXL', 'Xxl'), ('XXXL', 'Xxxl')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=10),
        ),
    ]
