# Generated by Django 5.0.6 on 2024-05-19 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.CharField(blank=True, choices=[('Jacket', 'Jacket'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('T-shirt', 'T Shirt'), ('Dress', 'Dress'), ('Skirt', 'Skirt'), ('Sweater', 'Sweater'), ('Coat', 'Coat'), ('Suit', 'Suit'), ('Blazer', 'Blazer'), ('Hoodie', 'Hoodie'), ('Cardigan', 'Cardigan'), ('Tank Top', 'Tank Top'), ('Leggings', 'Leggings'), ('Tracksuit', 'Tracksuit'), ('Underwear', 'Underwear'), ('Socks', 'Socks'), ('Cap', 'Cap'), ('Hat', 'Hat')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Under Armour', 'Under Armour'), ('The North Face', 'The North Face'), ('Gucci', 'Gucci'), ('Prada', 'Prada'), ('Armani', 'Armani'), ('Calvin Klein', 'Calvin Klein'), ('Gap', 'Gap')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
