# Generated by Django 5.0.6 on 2024-05-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_brands_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('n', 'not provided'), ('r', 'Red'), ('g', 'Green'), ('b', 'Blue'), ('y', 'Yellow'), ('c', 'Cyan'), ('m', 'Magenta'), ('w', 'White'), ('k', 'Black')], default='n', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('n', 'not provided'), ('m', 'male'), ('f', 'female'), ('o', 'other')], default='n', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('n', 'not provided'), ('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XXL', 'Xxl'), ('XXXL', 'Xxxl')], default='n', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('n', 'not provided'), ('Jacket', 'Jacket'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('T-shirt', 'T Shirt'), ('Dress', 'Dress'), ('Skirt', 'Skirt'), ('Sweater', 'Sweater'), ('Coat', 'Coat'), ('Suit', 'Suit'), ('Blazer', 'Blazer'), ('Hoodie', 'Hoodie'), ('Cardigan', 'Cardigan'), ('Tank Top', 'Tank Top'), ('Leggings', 'Leggings'), ('Tracksuit', 'Tracksuit'), ('Underwear', 'Underwear'), ('Socks', 'Socks'), ('Cap', 'Cap'), ('Hat', 'Hat')], default='n', max_length=50),
        ),
    ]
