# Generated by Django 5.0.6 on 2024-05-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_color_alter_product_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'ordering': ['id']},
        ),
        migrations.AddIndex(
            model_name='brands',
            index=models.Index(fields=['id'], name='shop_brands_id_b76742_idx'),
        ),
    ]
