# Generated by Django 5.0.6 on 2024-05-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_brands_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('not provided', 'Not Type'), ('Jacket', 'Jacket'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('T-shirt', 'T Shirt'), ('Dress', 'Dress'), ('Skirt', 'Skirt'), ('Sweater', 'Sweater'), ('Coat', 'Coat'), ('Suit', 'Suit'), ('Blazer', 'Blazer'), ('Hoodie', 'Hoodie'), ('Cardigan', 'Cardigan'), ('Tank Top', 'Tank Top'), ('Leggings', 'Leggings'), ('Tracksuit', 'Tracksuit'), ('Underwear', 'Underwear'), ('Socks', 'Socks'), ('Cap', 'Cap'), ('Hat', 'Hat')], default='not provided', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/product/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
        ),
    ]
