# Generated by Django 5.0.6 on 2024-05-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_image_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viewed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
