# Generated by Django 5.0.6 on 2024-05-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
