# Generated by Django 5.0.6 on 2024-05-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_sale_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
